[Liam] Clarify multiple data types and add info about metadata order
VerifiedInc/VerifiedInc.github.io pull request #203
Opened 2024-12-02 14:14 UTC by gabrielborgesdm

Clarify multiple data types and add info about metadata order

**1-Click Type definition**
![image](https://github.com/user-attachments/assets/ac03b89e-3ff8-45cb-88d9-fbd804c3331e)

**1-Click Example**
![image](https://github.com/user-attachments/assets/29d8bbdb-30cc-43ca-a1d2-57ced92a3336)

[Ticket]()

- https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07PUTUA0CD
- https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07PR4H98K0

## Changes
- Add comment to lines with multiple data types in 1ClickEntity type definition (to clarify behavior based on multi)
- Add info about values in arrays (when multi is enabled) being in the same order for credentials and credential metadata

## Testing
locally

## Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas _to a borderline excessive amount_
- [ ] I have made any relevant corresponding changes to the documentation including the project readme.
- [x] I have run and tested the changes locally
- [ ] If it is a core feature, I have added an appropriate amount of unit tests.
- [ ] Any dependent changes have been merged and published in upstream projects

2024-12-02 14:15 UTC, gabrielborgesdm commented on versioned_docs/version-2/1-click-signup/api-reference/types.mdx
> +            string     // Single credential value when `children` is not present and `multi` is false
I didn't phrase it like "set to `true/false`" here because I wanted to shorten the comments.

2024-12-02 23:05 UTC, liamhalemccarty requested changes
Lightly edited for clarity consistent ordering. Please review

2024-12-02 23:05 UTC, liamhalemccarty commented on versioned_docs/version-2/1-click-signup/api-reference/types.mdx
> +            string     // Single credential value when `children` is not present and `multi` is false
```suggestion
            string     // Single string value when `multi` is false and `children` isn't included in the credential requests
```

2024-12-02 23:05 UTC, liamhalemccarty commented on versioned_docs/version-2/1-click-signup/api-reference/types.mdx
> +            | [string] // Array of credential values when `multi` is true, but no `children`
```suggestion
            | [string] // Array of string values when `multi` is true and `children` isn't included in the credential requests
```

2024-12-02 23:05 UTC, liamhalemccarty commented on versioned_docs/version-2/1-click-signup/api-reference/types.mdx
> +            | Object   // Single credential value of type `Object` when `children` is present and `multi` is false
```suggestion
            | Object   // Single object value when `multi` is false and `children` is included in the credential requests
```

2024-12-02 23:05 UTC, liamhalemccarty commented on versioned_docs/version-2/1-click-signup/api-reference/types.mdx
> +            | [Object] // Array of credential values of type `Object` when `multi` is true and `children` is present
```suggestion
            | [Object] // Array of object values when `multi` is true and `children` is included in the credential requests
```

2024-12-05 17:03 UTC, liamhalemccarty approved these changes

2024-12-05 17:04 UTC, merged